import { readFile, writeFile, mkdir, cp, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = fileURLToPath(new URL('../', import.meta.url));
const read = (name) => readFile(path.join(root, name), 'utf8');
const site = JSON.parse(await read('src/content/site.json'));
const projects = JSON.parse(await read('src/content/projects.json'));
const esc = (s='') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow = '<span aria-hidden="true">↗</span>';
const nav = `<header class="site-header"><a class="wordmark" href="/" aria-label="Neal Shandilya, home"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 19V5l16 14V5M4 5h16M4 19h16"/><circle cx="4" cy="5" r="2"/><circle cx="20" cy="19" r="2"/></svg>Neal Shandilya<span class="wordmark-period">.</span></a><nav aria-label="Main navigation"><a href="/#work">Work</a><a href="/#problems">Problems</a><a href="/#notes">Notes</a><a href="/#about">About</a><a class="nav-contact" href="/#contact">Get in touch ${arrow}</a></nav></header>`;
const footer = `<footer class="site-footer"><a href="/">Neal Shandilya</a><span>Mathematics · Physics · Computation</span><a href="#top">Back to top ↑</a></footer>`;
function page(title, content, url='/', desc=site.description) {return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${site.origin}${url}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${site.origin}${url}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(desc)}"><meta name="theme-color" content="#f5f3ec"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/fonts/instrument-serif.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/site.css"><script type="module" src="/assets/site.js"></script><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Person',name:site.name,url:site.origin,sameAs:site.socials.map(x=>x.url),knowsAbout:['Mathematics','Physics','Computer science','Ramsey theory']}).replace(/</g,'\\u003c')}</script></head><body id="top"><a class="skip-link" href="#main">Skip to content</a>${nav}<main id="main">${content}</main>${footer}</body></html>`;}
const points = [[245,48],[425,139],[413,352],[241,431],[63,324],[75,125]];
const edges = points.flatMap((p,i)=>points.slice(i+1).map((q,j)=>({a:i,b:i+j+1,p,q})));
function graph(){return `<figure class="graph-figure"><div class="figure-top mono"><span>FIG. 01 — A SMALL CERTAINTY</span><span>K₆</span></div><svg class="ramsey-graph" viewBox="0 0 490 480" aria-label="Interactive complete graph on six vertices" role="group"><defs><pattern id="grid" width="28" height="28" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".8" fill="#bfc2c4"/></pattern></defs><rect width="490" height="480" fill="url(#grid)"/><circle class="construction" cx="245" cy="240" r="192"/><g class="triangle-fill" aria-hidden="true"></g>${edges.map(({a,b,p,q},i)=>`<g class="graph-edge" role="button" tabindex="0" data-edge="${i}" aria-label="Edge ${a+1} to ${b+1}, blue. Activate to change color." aria-pressed="false"><path class="edge-hit" d="M${p}L${q}"/><path class="edge-line" d="M${p}L${q}"/></g>`).join('')}${points.map(([x,y],i)=>`<circle class="graph-node" cx="${x}" cy="${y}" r="6"/><text x="${x+(x<245?-21:15)}" y="${y+5}" class="node-label">${i+1}</text>`).join('')}</svg><figcaption><div><span class="graph-status">Six points. Two colors.</span><p>Change an edge. A triangle always finds a way.</p></div><button type="button" class="reset-graph" aria-label="Reset graph">↺</button></figcaption><details class="edge-controls"><summary>Edge controls & the idea</summary><p>Click or tap an edge, or use the controls below. Blue edges are solid; rust edges are dashed. With six vertices, every coloring contains a single-color triangle.</p><div class="edge-control-row"><label for="edge-picker">Edge</label><select id="edge-picker">${edges.map(({a,b},i)=>`<option value="${i}">${a+1} ↔ ${b+1}</option>`).join('')}</select><button id="recolor-edge" type="button">Change color</button></div></details><span id="graph-announcement" class="sr-only" role="status" aria-live="polite"></span><noscript><p>With six points and two edge colors, a single-color triangle is inevitable. Enable JavaScript to recolor the edges.</p></noscript></figure>`;}
const work = `<section class="section" id="work"><div class="section-heading"><div><p class="eyebrow">01 / Selected work</p><h2>Following the question.</h2></div><p>From abstract structure<br>to things that have to work.</p></div><div class="work-grid">${projects.map((p,i)=>`<article class="work-item"><a class="work-link" href="/work/${p.slug}/"><div class="project-visual visual-${i}" aria-hidden="true">${i===0?'<span class="math-formula">N → (k)<sup>r</sup><sub>c</sub></span><span class="visual-caption">ORDER IS INEVITABLE</span>':i===1?'<svg viewBox="0 0 360 160"><path class="axis" d="M30 135H335M45 145V20"/><path d="M45 117C70 117 70 40 95 45S110 135 140 105S155 10 190 32S200 133 235 101S260 20 300 48S319 76 335 55"/><path class="prediction" d="M45 112C80 110 73 52 96 53S115 118 140 97S164 26 190 43S211 121 235 94S269 34 300 56S320 81 335 64"/></svg><span class="visual-caption">MODEL ↔ OBSERVATION</span>':'<span class="book-equation">Why does<br><em>this follow?</em></span><span class="visual-caption">FROM INTUITION TO PROOF</span>'}</div><div class="work-meta mono"><span>${esc(p.category)}</span><span>${esc(p.year||p.status)}</span></div><h3>${esc(p.title)} ${arrow}</h3><p>${esc(p.description)}</p><span class="project-context">${esc(p.context)}</span></a></article>`).join('')}</div></section>`;
const hero = `<section class="hero" aria-labelledby="hero-heading"><div class="hero-copy"><p class="eyebrow"><span class="blue-dot"></span> Mathematics · Physics · Computation</p><h1 id="hero-heading">Good problems<br>don’t stay in<br><em>one field.</em></h1><p class="hero-intro">I’m Neal. I move between proofs, programs,<br class="desktop-break"> and physical models—following the question<br class="desktop-break"> wherever it leads.</p><a class="text-link" href="#work">Explore my work <span aria-hidden="true">↓</span></a></div>${graph()}<div class="hero-bottom mono"><span>PROOFS. PROGRAMS. PHYSICAL INTUITION.</span><a href="#work">SCROLL TO EXPLORE ↓</a></div></section>`;
const problems=`<section class="problems-section" id="problems"><div class="problems-inner"><div class="problems-intro"><p class="eyebrow">02 / Problems worth keeping</p><h2>The question <br>comes <em>first.</em></h2><p>A few ideas that connect the work.<br>Open one and follow the thread.</p><span class="margin-note">There’s usually another way in. ↗</span></div><div class="question-list"><details><summary><span class="question-number">01</span><h3>How much structure<br>is inevitable?</h3><span class="expand" aria-hidden="true">+</span></summary><div class="question-body"><p>Ramsey theory starts with a disarmingly simple idea: enough disorder forces a pattern. The graph above is a small example—six vertices, two edge colors, and no way to avoid a single-color triangle.</p><a class="text-link" href="/work/ramsey-theory/">Follow the mathematics ${arrow}</a></div></details><details><summary><span class="question-number">02</span><h3>What makes a physical<br>problem simpler?</h3><span class="expand" aria-hidden="true">+</span></summary><div class="question-body"><p>A force diagram, a conservation law, or a useful approximation can change the shape of a problem. These are central tools in the mechanics and olympiad problems I work through and teach.</p><a class="text-link" href="/phystutor.html">Inside the teaching ${arrow}</a></div></details><details><summary><span class="question-number">03</span><h3>How do you turn intuition<br>into a proof?</h3><span class="expand" aria-hidden="true">+</span></summary><div class="question-body"><p>Seeing why something might be true and explaining why it must be true are different steps. My olympiad mathematics book is about helping students cross that gap, starting with early competition problems.</p><a class="text-link" href="/work/olympiad-book/">About the book ${arrow}</a></div></details></div></div></section>`;
const milestones=`<section class="section milestones-section" id="milestones"><div class="section-heading"><div><p class="eyebrow">03 / Along the way</p><h2>Practice leaves a trace.</h2></div><p>Some milestones in a longer<br>education in problem solving.</p></div><div class="milestone-list">${site.milestones.map(m=>`<div class="milestone"><span class="mono">${esc(m.year||'—')}</span><h3>${esc(m.title)}</h3><span>${esc(m.detail)}</span>${m.asset?`<a href="/${m.asset}" aria-label="View ${esc(m.title)} record">Record ${arrow}</a>`:'<span aria-hidden="true">·</span>'}</div>`).join('')}</div></section>`;
const notesData=JSON.parse(await read('src/content/notes.json'));
const notes=`<section class="section notes-section" id="notes"><div class="section-heading"><div><p class="eyebrow">04 / Writing & notes</p><h2>Understanding, written down.</h2></div></div><a class="book-feature" href="/work/olympiad-book/"><div class="book-spine" aria-hidden="true"><span>NOTES TOWARD</span><strong>A way into<br>olympiad<br><em>mathematics.</em></strong><span>NEAL SHANDILYA</span></div><div class="book-copy"><span class="eyebrow">Book in progress</span><h3>Make the path<br>easier to find.</h3><p>An introduction to olympiad mathematics, from early competition problems to proof-based thinking. Written for students who need a place to begin.</p><span class="book-status">Planned as a free resource.</span><span class="text-link">Read about the book ${arrow}</span></div></a>${notesData.length?`<div class="note-list">${notesData.map(n=>`<a href="/notes/${esc(n.slug)}/"><span class="mono">${esc(n.date||'Note')}</span><h3>${esc(n.title)}</h3>${arrow}</a>`).join('')}</div>`:''}</section>`;
const teaching=`<section class="teaching-section" id="teaching"><div class="teaching-inner"><div><p class="eyebrow">05 / Teaching</p><h2>An explanation should<br>leave you with<br><em>more intuition.</em></h2></div><div class="teaching-copy"><p>I teach physics and mathematics with an emphasis on clear reasoning, worked examples, and the step that makes a difficult idea click.</p><p>I want students to have the guidance and resources I wish I’d had when I started.</p><ul class="subject-list"><li>AP Physics 1, 2 & C: Mechanics</li><li>F=ma & competition problem solving</li><li>Calculus & school mathematics</li></ul><a class="text-link" href="/phystutor.html">Topics & tutoring details ${arrow}</a></div></div></section>`;
const about=`<section class="section about-section" id="about"><div><p class="eyebrow">06 / About</p><h2>Neal, beyond <br>the shorthand.</h2><span class="location mono">HOWARD COUNTY, MARYLAND</span></div><div class="about-copy"><p class="about-lead">I like problems where computation, mathematics, and physical intuition have something to say to each other.</p><p>My interests run from combinatorics and theoretical computer science to physics and language models. Sometimes that means a proof; sometimes a program; sometimes starting again with a better question.</p><p>Research, olympiads, competitive programming, and teaching are different ways of spending time with those questions. I care about making difficult ideas more accessible—and sharing the resources that help.</p><div class="interest-line"><span>Currently drawn to</span><p>Ramsey theory · Algorithms · AI & language models</p></div></div></section>`;
const contact=`<section class="section contact-section" id="contact"><p class="eyebrow">07 / Contact</p><h2>Have a good <em>question?</em></h2><div class="contact-bottom"><a class="email-link" href="mailto:${site.email}">${site.email} ${arrow}</a><div class="social-links">${site.socials.map(s=>`<a href="${esc(s.url)}">${esc(s.label)} ${arrow}</a>`).join('')}</div></div></section>`;
const out=new Map();
out.set('index.html',page('Neal Shandilya — Mathematics, Physics & Computation',hero+work+problems+milestones+notes+teaching+about+contact));
function article(kicker,title,lead,body){return `<article class="detail-page"><a class="back-link" href="/#work">← Back to selected work</a><header class="detail-heading"><p class="eyebrow">${kicker}</p><h1>${title}</h1><p class="detail-lead">${lead}</p></header>${body}</article>`;}
for(const p of projects){out.set(`work/${p.slug}/index.html`,page(`${p.title} — Neal Shandilya`,article(esc(p.category),esc(p.title),esc(p.description),`<div class="detail-meta"><span>${esc(p.context)}</span><span>${esc(p.year||p.status)}</span></div><div class="prose">${p.body.map(t=>`<p>${esc(t)}</p>`).join('')}<aside class="availability">${esc(p.availability)}</aside>${p.slug==='ramsey-theory'?'<h2>A small example</h2><p>Choose any vertex of a complete graph on six vertices. At least three of its five edges share a color. If any edge between those three neighbors has that color, it completes a triangle with the chosen vertex. Otherwise, the three neighbors form a triangle in the other color.</p><p>Five vertices can avoid such a triangle: color a five-cycle blue and the remaining edges rust. Six cannot.</p><a class="text-link" href="/">Try the graph ↑</a>':''}</div><ul class="tags">${p.tags.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`),`/work/${p.slug}/`,p.description));}
for(const n of notesData){
 if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(n.slug))throw Error('Invalid note slug');
 out.set(`notes/${n.slug}/index.html`,page(`${n.title} — Neal Shandilya`,article('Note',esc(n.title),esc(n.description),`<div class="prose">${n.body.map(t=>`<p>${esc(t)}</p>`).join('')}</div>`),`/notes/${n.slug}/`,n.description));
}
const courses=JSON.parse(await read('src/content/courses.json'));
const tutoring=article('Teaching','Start with the idea.','Physics and mathematics tutoring, built around clear explanations, worked examples, and focused practice.',`<div class="prose"><p>I work with students from elementary through high school, tailoring sessions to coursework, enrichment, and competition preparation. My physics teaching draws on experience with the 2026 USA Physics Team and olympiad problem solving.</p><p>Sessions can include custom handouts, guided examples, and targeted problems. Email me about your goals and the material you’re working on.</p></div><a class="text-link" href="mailto:${site.email}?subject=Tutoring%20inquiry">Ask about tutoring ${arrow}</a><section class="detail-section" aria-labelledby="topics-title"><p class="eyebrow">The material</p><h2 id="topics-title">Topics I teach</h2><p>These are teaching topics, tailored to your course and goals.</p><div class="curriculum">${courses.map(c=>`<details><summary><h3>${esc(c.title)}</h3><span class="expand" aria-hidden="true">+</span></summary><div class="topic-list">${c.topics.map(t=>`<details><summary>${esc(t.name)}<span aria-hidden="true">+</span></summary><ul>${t.sub.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></details>`).join('')}</div></details>`).join('')}</div></section><section class="detail-section" aria-labelledby="rates-title"><p class="eyebrow">One-to-one sessions</p><h2 id="rates-title">Tutoring rates</h2><div class="rates">${site.rates.map(r=>`<div><h3>${esc(r.subject)}<small>${esc(r.detail)}</small></h3><span>${esc(r.price)}</span></div>`).join('')}</div><p class="rate-note">For AP Physics 2 or a different topic, email me to discuss the scope and rate.</p></section><section class="detail-section" aria-labelledby="inquiry-title"><p class="eyebrow">Get in touch</p><h2 id="inquiry-title">What are you working on?</h2><form action="https://formspree.io/f/xnjwkbdv" method="POST" class="inquiry-form"><input type="hidden" name="_subject" value="New Physics Tutoring Request"><div class="form-pair"><label>Your name<input name="name" autocomplete="name" required></label><label>Email address<input type="email" name="email" autocomplete="email" required></label></div><label>Topic<input name="topic" required placeholder="e.g. F=ma, calculus, rotational dynamics"></label><label>Your question or goals<textarea name="message" rows="5" required></textarea></label><button class="submit-button" type="submit">Send tutoring inquiry ${arrow}</button><p class="form-note">This form sends your inquiry through Formspree. You can also email <a href="mailto:${site.email}">${site.email}</a>.</p></form></section>`);
out.set('phystutor.html',page('Teaching & tutoring — Neal Shandilya',tutoring,'/phystutor.html','Physics and mathematics tutoring with Neal Shandilya. Explore topics, session rates, and competition preparation.'));
// Keep legacy bookmarks useful; Pages does not provide configurable HTTP redirects.
for(const [file,hash,title] of [['about.html','about','About'],['research.html','work','Research'],['Proofs.html','milestones','Milestones']])out.set(file,page(`${title} — Neal Shandilya`,`<section class="detail-page"><p class="eyebrow">${title}</p><h1>This page has a new home.</h1><a class="text-link" href="/#${hash}">Continue to ${title.toLowerCase()} →</a></section>`,`/#${hash}`).replace('</head>',`<meta http-equiv="refresh" content="0;url=/#${hash}"></head>`));
out.set('essay-services.html',page('Essay services — Neal Shandilya',article('Application support','Essay services are closed.','Essay and application review services are closed for the 2026–2027 cycle / Class of 2027.','<div class="prose"><p>For physics or mathematics tutoring, visit <a href="/phystutor.html">teaching & tutoring</a>.</p></div>'),'/essay-services.html'));
out.set('404.html',page('Page not found — Neal Shandilya',`<section class="detail-page"><p class="eyebrow">404 / An unconnected node</p><h1>This path stops here.</h1><p>The page may have moved. There’s more to follow from the home page.</p><a class="text-link" href="/">Back to the beginning →</a></section>`,'/404.html').replace('index,follow','noindex,follow'));
const canonicalPaths=['/','/phystutor.html',...projects.map(p=>`/work/${p.slug}/`),...notesData.map(n=>`/notes/${n.slug}/`)];
out.set('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${canonicalPaths.map(p=>`<url><loc>${site.origin}${p}</loc></url>`).join('')}</urlset>`);
out.set('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${site.origin}/sitemap.xml\n`);
out.set('.nojekyll','');
await mkdir(path.join(root,'assets'),{recursive:true});
for(const f of ['site.css','site.js','graph.js'])await cp(path.join(root,'src/assets',f),path.join(root,'assets',f));
await rm(path.join(root,'dist'),{recursive:true,force:true});
await mkdir(path.join(root,'dist'),{recursive:true});
for(const [file,body] of out){
 for(const base of [root,path.join(root,'dist')]){await mkdir(path.dirname(path.join(base,file)),{recursive:true});await writeFile(path.join(base,file),body)}
}
for(const dir of ['assets','images'])await cp(path.join(root,dir),path.join(root,'dist',dir),{recursive:true});
console.log(`Built ${[...out.keys()].filter(f=>f.endsWith('.html')).length} static pages. No client framework or runtime dependencies.`);
